import json
import argparse
from jsondiff import diff

"""
Debug Script to check PUMAP generated by this converter against PUMAP generated by Project University
"""


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("real", metavar='Realfile Path',
                        type=str, help='- Absolute path to proper *.pumap file')
    parser.add_argument("compare", metavar='Comparefile Path',
                        type=str, help='- Absolute path to generated *.pumap file')
    args = parser.parse_args()

    real_path = args.real
    compare_path = args.compare

    with open(real_path) as real_file:
        with open(compare_path) as compare_file:
            real_obj = json.load(real_file)
            compare_obj = json.load(compare_file)

            print(diff(real_obj, compare_obj))


if __name__ == '__main__':
    main()
